export const LIST_ALL = 'LIST_ALL';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_SPECIFIC = 'FETCHING_SPECIFIC';
export const FETCHING_SPECIFIC_PRODUCT = 'FETCHING_SPECIFIC_PRODUCT';
export const AUTHENTICATION = 'AUTHENTICATION';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const ON_TOGGLE_SIDE_BAR = 'ON_TOGGLE_SIDE_BAR';
